import { Tag } from "lucide-react";

/** Flags a product whose barcode was scanned in as-is (not generated by Retake's own scheme). */
export function ExternalBarcodeBadge() {
  return (
    <span className="inline-flex items-center gap-1 rounded-full bg-amber-100 px-2 py-0.5 text-xs font-medium text-amber-800">
      <Tag size={12} aria-hidden />
      External
    </span>
  );
}
