"use client";

import { useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { PackageSearch, Tag } from "lucide-react";
import { ScannerInput } from "@/components/scanner/ScannerInput";
import { BarcodePanel } from "@/components/scanner/BarcodePanel";
import { ExternalBarcodeBadge } from "@/components/ExternalBarcodeBadge";
import { useLazyGetProductByBarcodeQuery, useLazyDecodeBarcodeQuery } from "@/lib/redux/features/products/productsApi";
import type { Product } from "@/types/product";
import type { DecodedBarcode } from "@/lib/redux/features/products/productsApi";

type ScanResult =
  | { status: "found"; product: Product }
  | { status: "unknown"; code: string; decoded: DecodedBarcode }
  | { status: "external"; code: string }
  | { status: "invalid"; code: string; message: string };

const EAN13_SHAPE = /^\d{13}$/;

export default function BarcodePage() {
  const [lookupByBarcode] = useLazyGetProductByBarcodeQuery();
  const [decodeBarcode] = useLazyDecodeBarcodeQuery();
  const [result, setResult] = useState<ScanResult | null>(null);
  const [isChecking, setIsChecking] = useState(false);

  async function handleScan(code: string) {
    setIsChecking(true);
    try {
      const product = await lookupByBarcode(code).unwrap();
      setResult({ status: "found", product });
    } catch {
      try {
        const decoded = await decodeBarcode(code).unwrap();
        setResult({ status: "unknown", code, decoded });
      } catch (err) {
        if (EAN13_SHAPE.test(code)) {
          // Well-formed EAN-13, just not generated by Retake — likely a third-party product's own barcode.
          setResult({ status: "external", code });
        } else {
          const message =
            err && typeof err === "object" && "data" in err
              ? (err.data as { message?: string })?.message
              : undefined;
          setResult({ status: "invalid", code, message: message ?? "Not a recognized barcode." });
        }
      }
    } finally {
      setIsChecking(false);
    }
  }

  return (
    <div className="mx-auto max-w-lg">
      <h1 className="text-2xl font-semibold text-foreground">Barcode</h1>
      <p className="mt-1 text-sm text-muted">
        Scan with a USB/Bluetooth scanner, or type a code and press Enter — works for looking up
        stock or generating a printable label.
      </p>

      <div className="mt-4">
        <ScannerInput onScan={handleScan} />
      </div>

      {isChecking && <p className="mt-4 text-sm text-muted">Checking…</p>}

      {result?.status === "found" && (
        <div className="mt-4 flex flex-col gap-4">
          <Link
            href={`/products/${result.product._id}`}
            className="flex items-center gap-3 rounded-lg border border-border bg-background p-3 hover:border-primary"
          >
            <Image src={result.product.image} alt={result.product.name} width={48} height={48} className="rounded-md object-cover" />
            <div>
              <p className="flex items-center gap-2 text-sm font-medium text-foreground">
                {result.product.name} · {result.product.type} · {result.product.weightLabel}
                {result.product.barcodeSource === "external" && <ExternalBarcodeBadge />}
              </p>
              <p className="text-xs text-muted">
                SKU {result.product.sku} · {result.product.quantityInStock} in stock
              </p>
            </div>
          </Link>
          <BarcodePanel key={result.product._id} productId={result.product._id} sku={result.product.sku} ean13={result.product.ean13} />
        </div>
      )}

      {result?.status === "unknown" && (
        <div className="mt-4 rounded-lg border border-border bg-surface p-4">
          <div className="flex items-center gap-2 text-foreground">
            <PackageSearch size={18} aria-hidden />
            <p className="text-sm font-medium">Not in inventory yet</p>
          </div>
          <p className="mt-1 text-sm text-muted">
            {result.code} decodes to {result.decoded.productName} · {result.decoded.type} ·{" "}
            {result.decoded.weightLabel}, but no product with this barcode has been added.
          </p>
          <Link
            href={`/products/new?name=${encodeURIComponent(result.decoded.productName)}&type=${result.decoded.type}&weightLabel=${result.decoded.weightLabel}`}
            className="mt-3 inline-block rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground"
          >
            Add this product
          </Link>
        </div>
      )}

      {result?.status === "external" && (
        <div className="mt-4 rounded-lg border border-amber-300 bg-amber-50 p-4">
          <div className="flex items-center gap-2 text-foreground">
            <Tag size={18} aria-hidden />
            <p className="text-sm font-medium">Not a Retake barcode</p>
          </div>
          <p className="mt-1 text-sm text-muted">
            {result.code} is a valid barcode, but it wasn&apos;t generated by Retake — likely a
            third-party product. You can still add it, using this exact code as its barcode.
          </p>
          <Link
            href={`/products/new?barcode=${result.code}`}
            className="mt-3 inline-block rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground"
          >
            Add as external product
          </Link>
        </div>
      )}

      {result?.status === "invalid" && (
        <div className="mt-4 rounded-lg border border-border bg-surface p-4">
          <p className="text-sm font-medium text-danger">Invalid barcode</p>
          <p className="mt-1 text-sm text-muted">
            &quot;{result.code}&quot; — {result.message}
          </p>
        </div>
      )}
    </div>
  );
}
